name: Sync Branches

on:
  push:
    branches:
      - MahaS1Branch
      - RohitS1Branch
      - RohitS2Branch

jobs:
  sync-branches:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Git
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"

    - name: Get current branch
      id: get_branch
      run: echo "::set-output name=branch::$(git rev-parse --abbrev-ref HEAD)"
    
    - name: Sync with MahaS1Branch
      if: steps.get_branch.outputs.branch != 'MahaS1Branch'
      run: |
        git checkout MahaS1Branch
        git merge ${{ steps.get_branch.outputs.branch }} --no-ff
        git push origin MahaS1Branch

    - name: Sync with RohitS1Branch
      if: steps.get_branch.outputs.branch != 'RohitS1Branch'
      run: |
        git checkout RohitS1Branch
        git merge ${{ steps.get_branch.outputs.branch }} --no-ff
        git push origin RohitS1Branch

    - name: Sync with RohitS2Branch
      if: steps.get_branch.outputs.branch != 'RohitS2Branch'
      run: |
        git checkout RohitS2Branch
        git merge ${{ steps.get_branch.outputs.branch }} --no-ff
        git push origin RohitS2Branch
